# Generated by Django 3.1.7 on 2021-04-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
