# Generated by Django 3.1.7 on 2021-04-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210417_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_last_updated',
            new_name='updated_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='test-slug', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting approval'), (1, 'Approved'), (3, 'Deactivated')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
