# Generated by Django 3.1.7 on 2021-04-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210417_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Awaiting Approval'), ('Approved', 'Approved'), ('Deactivated', 'Deactivated')], default='Waiting', max_length=100),
        ),
    ]
