# Generated by Django 3.1.7 on 2021-08-13 13:33

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slack_display_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_unique_filename),
        ),
    ]
