# Generated by Django 3.1.7 on 2021-08-13 13:33

from django.db import migrations, models
import helpers


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_unique_filename),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.get_unique_filename),
        ),
    ]
